import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import cn from './lib/utils'
import Navbar from './component/Nabar'
import Tagger from './component/Tagger'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'InsightPDF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
      <body className={cn('min-hscreen font-sans antialised grainy', inter.className)}>
        <Navbar />
        {children}
        <Tagger />
        </body>
    </html>
  )
}
